# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{plancast}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wynn Netherland"]
  s.date = %q{2010-03-21}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{wynn.netherland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/plancast.rb",
     "lib/plancast/client.rb",
     "test/fixtures/attend.json",
     "test/fixtures/comment.json",
     "test/fixtures/create_friendship.json",
     "test/fixtures/featured.json",
     "test/fixtures/home_timeline.json",
     "test/fixtures/parse_when.json",
     "test/fixtures/plan.json",
     "test/fixtures/search.json",
     "test/fixtures/subscribers.json",
     "test/fixtures/subscriptions.json",
     "test/fixtures/unattend.json",
     "test/fixtures/update.json",
     "test/fixtures/user.json",
     "test/fixtures/user_search.json",
     "test/fixtures/user_timeline.json",
     "test/fixtures/verify_credentials.json",
     "test/helper.rb",
     "test/test_plancast.rb"
  ]
  s.homepage = %q{http://github.com/pengwynn/plancast}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "test/helper.rb",
     "test/test_plancast.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

